CREATE TABLE Addresses (
    AddressID INT IDENTITY(1,1) PRIMARY KEY,
    StreetAddress NVARCHAR(100) NOT NULL,
    City NVARCHAR(50) NOT NULL,
    State NVARCHAR(3) NOT NULL,
    PostalCode NVARCHAR(4) NOT NULL,
    Country NVARCHAR(50) NOT NULL DEFAULT 'Australia',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);